### ISSUE TITLE
美图 DPoS 实现相关问题

### ISSUE THREAD

**Issue by git-hulk** [meitu/go-ethereum#2]

**Comment by myself659** [comment]
美图DPoS是如何测试与验证？

**Comment by git-hulk** [comment]
@myself659 wiki 已补充相关内容, https://github.com/meitu/go-ethereum/wiki/

**Comment by wx7063** [comment]
出块时间修改没？ 投票方暴露ip吗？evm的最长执行时间修改没？

**Comment by wx7063** [comment]
出块时间修改没？ 投票方暴露ip吗？evm的最长执行时间修改没？

**Comment by wx7063** [comment]
出块时间修改没？ 投票方暴露ip吗？evm的最长执行时间修改没？

**Comment by fpcfjf** [comment]
投票不是自动进行的，我看WIKI上还要手动调用交易处理？

**Comment by pioneerlfn** [comment]
1.RPC模块中，什么情况下需要client.go中的逻辑处理，什么情况下直接到server.go?几种rpc, 包括console, 钱包，还有网页调用在以太坊内部的处理分叉在哪里？
	
2.blockchain的reorg逻辑能讲一下么？

**Comment by andy7716884** [comment]
在centos6.5环境下搭建美图开源的Dpos 以太坊，进行miner.start()测试时出现报错：“Failed to mint the block    err="failed to decode validators: EOF"”，请问是什么原因？？

**Comment by liguangbo** [comment]
@andy7716884 请问有使用正确的创世块文件初始化创世块吗？

**Comment by andy7716884** [comment]
使用http://t.im/2b4m里面的创世块文件报错消失，但是进行miner.start(1)返回null，而eth.blocknumber挖币数量一直为0，这是什么问题？

**Comment by liguangbo** [comment]
@andy7716884 具体表现是没有开始挖矿吗？创世块文件里面的validators是否都更换成你的节点的账号了呢？否则你的节点不是validator是没有办法尽心出块的呢。

**Comment by andy7716884** [comment]
单节点运行，validators更换了节点信息，一直显示在Staring mining operation都没有反应了，在原始版以太坊一样木有问题··

**Comment by liguangbo** [comment]
@andy7716884 创世文件和启动时的welcome截图。以及
```
> eth.validator
```
的执行结果方便发一下吗？

**Comment by andy7716884** [comment]
1.启动时的welcome截图和eth.validator执行结果
http://chuantu.biz/t6/336/1530258804x-1566688700.png

2.创世文件
http://chuantu.biz/t6/336/1530258859x-1376440252.png

**Comment by liguangbo** [comment]
@andy7716884 不好意思。漏了一个命令
```
> dpos.getValidators()
```

**Comment by andy7716884** [comment]
3.dpos.getValidators()
http://chuantu.biz/t6/336/1530260123x-1376440252.png

**Comment by liguangbo** [comment]
@andy7716884 
![image](https://user-images.githubusercontent.com/13741813/42081685-a9ac0392-7bb8-11e8-93ee-4eb98047a87c.png)

![](http://chuantu.biz/t6/336/1530260123x-1376440252.png)
你的账户并不在validators里面。修改了创世文件。需要删除datadir里面的geth目录，然后重新执行init操作才行哈

**Comment by andy7716884** [comment]
嗯，删除重建geth文件，再重新执行miner.start（）又有新报错了，
http://chuantu.biz/t6/336/1530261546x-1376440252.png

**Comment by liguangbo** [comment]
@andy7716884 
这个问题如字面描述，麻烦确认一下[文档里面](https://github.com/meitu/go-ethereum/wiki/%E6%90%AD%E5%BB%BA%E7%A7%81%E9%93%BE#%E7%BC%96%E8%AF%91)
这一段，是否有把参数设置为1然后进行编译。如果没有的话，单节点启动，validator数量不足够进行选举，启动会失败。

**Comment by andy7716884** [comment]
好，原来为5，修改为1就可以了，谢谢哈！另想问问有没搭建公有链的实例？

**Comment by liguangbo** [comment]
@andy7716884 没有哈，目前还是做一些技术尝试

**Comment by andy7716884** [comment]
你是meitu团队的吗？有没相关技术Q群推荐一下哈，目前在学习ing，方便也可以+V，哈哈？

**Comment by liguangbo** [comment]
@andy7716884 是的，可以把你微信发我邮箱，拉你进群

**Comment by andy7716884** [comment]
好的，已发邮件，谢谢哈！
