### ISSUE TITLE
lookupValidator?

### ISSUE THREAD

**Issue by dtest11** [meitu/go-ethereum#7]
```go

func (ec *EpochContext) lookupValidator(now int64) (validator common.Address, err error) {
	validator = common.Address{}
	offset := now % epochInterval  // the 
	if offset%blockInterval != 0 {
		return common.Address{}, ErrInvalidMintBlockTime
	}
	offset /= blockInterval

	validators, err := ec.DposContext.GetValidators()
	if err != nil {
		return common.Address{}, err
	}
	validatorSize := len(validators)
	if validatorSize == 0 {
		return common.Address{}, errors.New("failed to lookup validator")
	}
	offset %= int64(validatorSize)
	return validators[offset], nil
}

```

The purpose of setting this variable ```epochInterval```, how to set the value of this variable, what are the conditions? and Can you explain the implementation principle of this function? ths.

**Comment by git-hulk** [comment]
The meaning of `epochInterval` is the epoch window to re-elect the new validators. It's hard code at Line: https://github.com/meitu/go-ethereum/blob/ac7c567ec16e4a7dbb39a8534a3792688460a4a6/consensus/dpos/dpos.go#L35 , means re-elect the validators every day.

**Comment by dtest11** [comment]
if i wan to set the value , Is there anything I have to pay attention to?， like set epochInterval = 1000

**Comment by git-hulk** [comment]
@viperlin it's ok for the test, but it should be at least one day on production
